/** Textos de interfaz en español de Chile. */
import type { GroupEventKind } from './api';

export const strings = {
  appName: 'Te Tocó',
  common: {
    loading: 'Cargando…',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    back: 'Volver',
    goHome: 'Ir al inicio',
    optional: 'opcional',
  },
  home: {
    title: 'Mis grupos',
    empty: 'Todavía no estás en ningún grupo.',
    createGroup: 'Crear un grupo',
    haveLink: 'Tengo un link',
    linkPlaceholder: 'Pega aquí tu link',
    openLink: 'Abrir',
    invalidLink: 'Ese no parece un link de Te Tocó.',
    settings: 'Ajustes',
    owner: 'Organizas',
    unread: (n: number) => (n === 1 ? '1 mensaje nuevo' : `${n} mensajes nuevos`),
  },
  status: {
    open: 'Sin sorteo',
    drawn: 'Sorteado',
    archived: 'Terminado',
  },
  login: {
    title: 'Iniciar sesión',
    explain: 'Para crear un grupo tienes que entrar con Google. Para participar basta con tu link.',
    google: 'Continuar con Google',
    devTitle: 'Solo en desarrollo',
    email: 'Correo',
    password: 'Contraseña',
    signIn: 'Entrar',
    signUp: 'Crear cuenta',
    checkEmail: 'Te enviamos un correo para confirmar la cuenta. Confírmala y vuelve a entrar.',
    googleFailed: 'No se pudo iniciar sesión con Google.',
    googleAlreadyUsed:
      'Esa cuenta de Google ya está en uso. Inicia sesión con ella desde Ajustes para traer tus grupos.',
  },
  invite: {
    opening: 'Abriendo tu link…',
    claimedByOtherTitle: 'Este link ya se abrió en otro dispositivo',
    claimedByOtherHelp:
      'Ábrelo en el teléfono o navegador donde lo abriste la primera vez. Si ya no lo tienes, pídele a quien organiza que regenere tu link.',
    alreadyMemberTitle: 'Ya eres parte de este grupo',
    alreadyMemberHelp: 'Entraste a este grupo con otro nombre. Cada persona tiene un solo link.',
    invalidTitle: 'Link no válido',
    invalidHelp: 'Puede que lo hayan regenerado. Pídele a quien organiza tu link nuevo.',
  },
  newGroup: {
    title: 'Nuevo grupo',
    name: 'Nombre del grupo',
    namePlaceholder: 'Familia 2026',
    date: 'Fecha del evento',
    place: 'Lugar',
    budget: 'Presupuesto por regalo (CLP)',
    participate: 'Yo también participo',
    myName: 'Mi nombre en el grupo',
    create: 'Crear grupo',
  },
  group: {
    manage: 'Administrar',
    archivedNotice: 'El evento ya pasó: el grupo quedó en solo lectura.',
    budget: 'Presupuesto',
    place: 'Lugar',
    myResult: 'Mi resultado',
    noDraw: 'Aún no hay sorteo',
    notParticipating: 'No participas en este sorteo.',
    reveal: 'Revelar',
    youGiveTo: 'Te tocó regalarle a',
    theirWishlist: 'Su lista de deseos',
    emptyTheirWishlist: 'Todavía no escribe su lista.',
    myWishlist: 'Mi lista de deseos',
    emptyMyWishlist: 'Agrega ideas para que sepan qué regalarte.',
    wishText: 'Qué te gustaría',
    wishUrl: 'Link (opcional)',
    addWish: 'Agregar',
    wishLimit: 'Llegaste al máximo de 10 ideas.',
    participants: 'Participantes',
    openedLink: 'Abrió su link',
    notOpenedLink: 'No ha abierto su link',
    viewedResult: 'Vio su resultado',
    notViewedResult: 'No ha visto su resultado',
    you: 'tú',
    activity: 'Actividad',
    noActivity: 'Sin actividad todavía.',
  },
  manage: {
    title: 'Administrar',
    details: 'Detalles del evento',
    participants: 'Participantes',
    addPlaceholder: 'Nombre de la persona',
    add: 'Agregar',
    share: 'Compartir',
    rename: 'Renombrar',
    remove: 'Quitar',
    regenerate: 'Regenerar link',
    shareMessage: (name: string, group: string, link: string) =>
      `Hola ${name}, te invito al Amigo Secreto de ${group}: ${link}`,
    removeConfirm: (name: string) => `¿Quitar a ${name}? Se borran sus exclusiones y su lista de deseos.`,
    regenerateConfirm: (name: string) =>
      `El link actual de ${name} dejará de funcionar y todo el grupo lo verá en la actividad. ¿Continuar?`,
    exclusions: 'Exclusiones',
    exclusionsHelp: 'Quién no puede regalarle a quién. Una pareja excluye ambos sentidos.',
    noExclusions: 'Sin exclusiones.',
    giver: 'Quien regala',
    receiver: 'No le puede regalar a',
    couple: 'Es pareja (ambos sentidos)',
    addExclusion: 'Agregar exclusión',
    exclusionRow: (giver: string, receiver: string) => `${giver} no le regala a ${receiver}`,
    options: 'Opciones del sorteo',
    avoidMutual: 'Evitar pares mutuos',
    avoidMutualHelp: 'Nadie le regala a quien le regala a él o ella.',
    singleCycle: 'Una sola cadena',
    singleCycleHelp: 'Todos forman un único círculo de regalos.',
    draw: 'Sortear',
    drawConfirm: 'Nadie, ni siquiera tú, podrá ver el resultado completo. ¿Sortear ahora?',
    drawDone: '¡Listo! Ya está el sorteo.',
    reset: 'Repetir sorteo',
    resetConfirm:
      'Se borran las asignaciones, los mensajes y quién vio su resultado. Se mantienen los participantes, sus links y las listas de deseos. Todo el grupo lo verá en la actividad. ¿Repetir?',
    deleteGroup: 'Eliminar grupo',
    deleteConfirm: 'Se borra el grupo con todo su contenido. No se puede deshacer.',
    lockedAfterDraw: 'Después del sorteo no se pueden cambiar participantes, exclusiones ni opciones.',
  },
  settings: {
    title: 'Ajustes',
    account: 'Cuenta',
    anonymous: 'Entraste con tu link, sin cuenta.',
    signedInAs: (email: string) => `Sesión iniciada como ${email}`,
    saveWithGoogle: 'Guardar con Google',
    saveWithGoogleHelp: 'Para no perder tus grupos al cambiar de teléfono.',
    privacy: 'Política de privacidad',
    deleteAccount: 'Eliminar mi cuenta',
    version: (v: string) => `Versión ${v}`,
    signOut: 'Cerrar sesión (desarrollo)',
  },
  activity: {
    member_added: (name: string) => `Se agregó a ${name}`,
    member_renamed: (name: string) => `Se renombró a ${name}`,
    member_removed: (name: string) => `Se quitó a ${name}`,
    invite_claimed: (name: string) => `${name} abrió su link`,
    invite_regenerated: (name: string) => `Se regeneró el link de ${name}`,
    draw_done: () => 'Se hizo el sorteo',
    draw_reset: () => 'Se repitió el sorteo',
    result_viewed: (name: string) => `${name} vio su resultado`,
  } satisfies Record<GroupEventKind, (name: string) => string>,
} as const;
